### ISSUE TITLE
Script doesn't work on localized pages

### ISSUE THREAD

**Issue by Destroy666x** [echandler/Geoguessr-Unity-Script-Fork#1]
E.g. `https://geoguessr.com/pl/game/...`, as `startsWith` doesn't recognize the language code.

```
const isGamePage = () => location.pathname.startsWith("/challenge/") || location.pathname.startsWith("/results/") ||
                  location.pathname.startsWith("/game/")|| location.pathname.startsWith("/battle-royale/") ||
                  location.pathname.startsWith("/duels/") || location.pathname.startsWith("/team-duels/") || location.pathname.startsWith("/bullseye/")
            || location.pathname.startsWith("/live-challenge/");
```
needs to be replaced with something like:
```
const path = location.pathname.replace(/^\/[a-z]{2}\//i, "/");
const isGamePage = () => path.startsWith("/challenge/") || path.startsWith("/results/") ||
                  path.startsWith("/game/")|| path.startsWith("/battle-royale/") ||
                  path.startsWith("/duels/") || path.startsWith("/team-duels/") || path.startsWith("/bullseye/")
                  || path.startsWith("/live-challenge/");
```

Original author ignored my Discord messages, just found this, so would be nice to fix it here at least, too bad it's not on GreasyFork though.

**Comment by echandler** [comment]
Wow, sorry for the late reply, I just saw this a few hours ago. It tries to detect the pathname in numerous places, but I think making a function with your regex may have fixed it. I'll try to keep an eye on this issue, and hopefully the original dev will take back his project. No idea why he abandoned it.
